/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper */

#ifndef _Included_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
#define _Included_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_UNEXPECTED
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_UNEXPECTED 1L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_ENOUGH_MEMORY
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_ENOUGH_MEMORY 100L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_UNSUPPORTED
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_UNSUPPORTED 101L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NAME_TOOLONG
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NAME_TOOLONG 102L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_A_DIRECTORY
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_A_DIRECTORY 103L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_FILE_NOT_FOUND
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_FILE_NOT_FOUND 104L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_BUFFER_TOO_SMALL
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_BUFFER_TOO_SMALL 105L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_ATTRIBUTE_NOT_FOUND
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_ATTRIBUTE_NOT_FOUND 106L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_INVALID_DATA
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_INVALID_DATA 107L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_ENOUGH_DISK_SPACE
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_ENOUGH_DISK_SPACE 108L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_PERMISSION_DENIED
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_PERMISSION_DENIED 109L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_RO_FILESYSTEM
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_RO_FILESYSTEM 110L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_DISK_QUOTA
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_DISK_QUOTA 111L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_INTERNAL
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_INTERNAL 112L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_IO
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_IO 113L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_IMPLEMENTED
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_NOT_IMPLEMENTED 114L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_LOOP
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_LOOP 115L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_ACCESS_DENIED
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_ERR_ACCESS_DENIED 116L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_MASK_PERMISSION
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_MASK_PERMISSION 4095L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_MASK_TYPE
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_MASK_TYPE 61440L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_LINK
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_LINK 40960L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_SOCKET
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_SOCKET 49152L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_CHARSPECFILE
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_CHARSPECFILE 8192L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_BLOCKSPECIALFILE
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_BLOCKSPECIALFILE 24576L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_FILE
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_FILE 32768L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_DIRECTORY
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_DIRECTORY 16384L
#undef com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_PIPE
#define com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_TYPE_PIPE 4096L
/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getData
 * Signature: (Ljava/lang/String;Z)Lcom/myJava/file/metadata/posix/jni/wrapper/GetDataResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getData
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    setFileOwner
 * Signature: (Ljava/lang/String;IIZ)Lcom/myJava/file/metadata/posix/jni/wrapper/SetFileOwnerResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_setFileOwner
  (JNIEnv *, jclass, jstring, jint, jint, jboolean);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    setFileModeImpl
 * Signature: (Ljava/lang/String;I)Lcom/myJava/file/metadata/posix/jni/wrapper/SetFileModeResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_setFileModeImpl
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getGroupId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getGroupId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getGroupName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getGroupName
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getUserId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getUserId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getUserName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getUserName
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getAttributeNames
 * Signature: (Ljava/lang/String;IZ)Lcom/myJava/file/metadata/posix/jni/wrapper/GetAttributeNamesResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getAttributeNames
  (JNIEnv *, jclass, jstring, jint, jboolean);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getAttributeValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;JZ)Lcom/myJava/file/metadata/posix/jni/wrapper/GetAttributeValueResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getAttributeValue
  (JNIEnv *, jclass, jstring, jstring, jlong, jboolean);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    setAttributeValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BZ)Lcom/myJava/file/metadata/posix/jni/wrapper/SetAttributeValueResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_setAttributeValue
  (JNIEnv *, jclass, jstring, jstring, jbyteArray, jboolean);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    getACL
 * Signature: (Ljava/lang/String;Z)Lcom/myJava/file/metadata/posix/jni/wrapper/GetACLResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_getACL
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper
 * Method:    setACL
 * Signature: (Ljava/lang/String;Lcom/myJava/file/metadata/posix/ACL;IZ)Lcom/myJava/file/metadata/posix/jni/wrapper/SetACLResult;
 */
JNIEXPORT jobject JNICALL Java_com_myJava_file_metadata_posix_jni_wrapper_FileAccessWrapper_setACL
  (JNIEnv *, jclass, jstring, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
